#!/bin/bash

print(){
    echo VIRSH_GPU_VIDEO=pci_0000_$1_$2_0 > kvm.conf
    echo VIRSH_GPU_AUDIO=pci_0000_$1_$2_1 >> kvm.conf
};

PT1=$(lspci -nnk | grep VGA | grep -oP '\d+(?=:\d{2}(?=\.))');
PT2=$(lspci -nnk | grep VGA | grep -oP '(?<=:)\d+(?=\.)');

print $PT1 $PT2